name: trekcure
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
   
  # Network
  http: ^1.6.0
  
  crypto: ^3.0.6 
  
  # UI
  google_fonts: ^6.2.1

  # Notifications
  flutter_local_notifications: ^22.3.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0

  # Local storage
  shared_preferences: ^2.5.5
  # Supabase
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2

  # Maps and location
  flutter_map: ^7.0.2
  flutter_map_heatmap: ^0.0.8
  latlong2: ^0.9.1
  geolocator: ^14.0.3
  geocoding: ^5.0.0

  # Offline mesh
  nearby_connections: ^4.3.0

  # Permissions
  permission_handler: ^12.0.0

  #Scanner
  mobile_scanner: ^7.2.0

  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Application images
  assets:
    - asset/images/login_travel.jpeg