// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxkMywOG4OdhsvBPRDgVCEEcaQuAj4XVY',
    appId: '1:555319363949:web:b3d771fc0c3511ac057264',
    messagingSenderId: '555319363949',
    projectId: 'trekcure-d8637',
    authDomain: 'trekcure-d8637.firebaseapp.com',
    storageBucket: 'trekcure-d8637.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4nJYhz9kru4riYVx7cq44icnueUpWhQ',
    appId: '1:555319363949:android:6dcab9121f38aaed057264',
    messagingSenderId: '555319363949',
    projectId: 'trekcure-d8637',
    storageBucket: 'trekcure-d8637.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1cxUBHtNVGfkxE_Qi0y-8N0vVw18iVys',
    appId: '1:555319363949:ios:614465e9dad1acdb057264',
    messagingSenderId: '555319363949',
    projectId: 'trekcure-d8637',
    storageBucket: 'trekcure-d8637.firebasestorage.app',
    iosBundleId: 'com.example.trekcure',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1cxUBHtNVGfkxE_Qi0y-8N0vVw18iVys',
    appId: '1:555319363949:ios:614465e9dad1acdb057264',
    messagingSenderId: '555319363949',
    projectId: 'trekcure-d8637',
    storageBucket: 'trekcure-d8637.firebasestorage.app',
    iosBundleId: 'com.example.trekcure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxkMywOG4OdhsvBPRDgVCEEcaQuAj4XVY',
    appId: '1:555319363949:web:b9f0b4daae89bbd3057264',
    messagingSenderId: '555319363949',
    projectId: 'trekcure-d8637',
    authDomain: 'trekcure-d8637.firebaseapp.com',
    storageBucket: 'trekcure-d8637.firebasestorage.app',
  );
}
