// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF5ESGY4OZfxj_xw7XTTN3SFKu-9wwCCI',
    appId: '1:991959032874:web:06b7ac26e1aa4de4b30f53',
    messagingSenderId: '991959032874',
    projectId: 'trekcure-910c1',
    authDomain: 'trekcure-910c1.firebaseapp.com',
    storageBucket: 'trekcure-910c1.firebasestorage.app',
    measurementId: 'G-6QGL5V8Y3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcrRz3JCYz-_eRkHq5ewkLGFLf2MiFFrQ',
    appId: '1:991959032874:android:b0ddfb5b1e72c052b30f53',
    messagingSenderId: '991959032874',
    projectId: 'trekcure-910c1',
    storageBucket: 'trekcure-910c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvYHYNdC4uWvc5UsXwlyh4r-lY7r_s-CY',
    appId: '1:991959032874:ios:74bf05e45b3017feb30f53',
    messagingSenderId: '991959032874',
    projectId: 'trekcure-910c1',
    storageBucket: 'trekcure-910c1.firebasestorage.app',
    iosBundleId: 'com.example.trekcure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvYHYNdC4uWvc5UsXwlyh4r-lY7r_s-CY',
    appId: '1:991959032874:ios:74bf05e45b3017feb30f53',
    messagingSenderId: '991959032874',
    projectId: 'trekcure-910c1',
    storageBucket: 'trekcure-910c1.firebasestorage.app',
    iosBundleId: 'com.example.trekcure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF5ESGY4OZfxj_xw7XTTN3SFKu-9wwCCI',
    appId: '1:991959032874:web:f65a1b4857a7976bb30f53',
    messagingSenderId: '991959032874',
    projectId: 'trekcure-910c1',
    authDomain: 'trekcure-910c1.firebaseapp.com',
    storageBucket: 'trekcure-910c1.firebasestorage.app',
    measurementId: 'G-7CE392FSMJ',
  );
}
